development:
  adapter: mysql
  database: test
  username: root
  username: root
  pool: 5
  timeout: 5000

test:
  adapter: mysql
  database: test
  username: root
  username: root
  pool: 5
  timeout: 5000

production:
  adapter: mysql
  database: test
  username: root
  username: root
  pool: 5
  timeout: 5000
